### ISSUE TITLE
'Color Overlay: Inactive' bug

### ISSUE THREAD

**Issue by bushpig10** [inimicus/GrimFocusCounter#4]
**When does the bug occur?**

when the grim(relentless) focus buff fades

**What is the expected behavior?**

the color of the display counter should change to red (or any selected color) when the buff fades, letting me know my 5 stacks are inactive and refreshing is neccessary to use them

**What is the actual behavior?**

the color of the counter stays the same color as it was before the buff fades. which may be either 'Color overlay: default' or 'Color overlay: Proc"

my settings
![image](https://github.com/inimicus/GrimFocusCounter/assets/137927368/63567160-908e-44a2-9ca3-6a1541da37b5)

how it looks while buff is active (correct)
![image](https://github.com/inimicus/GrimFocusCounter/assets/137927368/5ee0bbea-a2e4-4e42-a468-37b98effc3a8)

how it looks while buff is inactive (should be red)
![image](https://github.com/inimicus/GrimFocusCounter/assets/137927368/760ac9c4-031c-4b23-a57a-140fbecfd0c9)

**Comment by inimicus** [comment]
Thanks for the report! This helps to confirm #3.

**Comment by bushpig10** [comment]
no problem

**Comment by bushpig10** [comment]
it used to work fyi
